// Generated by klt functional-verification -- do not edit.
// Transparent pass-through wrapper working around Icarus's
// inability to resolve a top-level-port INTERCONNECT entry
// against a module elaborated as its own -s root (issue #1056).
module klt_sdf_dut_wrapper (
  input clk,
  output done,
  input rst_n,
  input start,
  input [15:0] base_in,
  input [15:0] exp_in,
  input [15:0] mod_in,
  output [15:0] result
);
  modexp klt_sdf_dut (
    .clk(clk),
    .done(done),
    .rst_n(rst_n),
    .start(start),
    .base_in(base_in),
    .exp_in(exp_in),
    .mod_in(mod_in),
    .result(result)
  );
endmodule
